workflows:
  ios_unsigned_ipa:
    name: iOS unsigned IPA (Flutter)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign

      - name: Create unsigned IPA artifact
        script: |
          mkdir -p $CM_ARTIFACTS_DIR
          cd build/ios/iphoneos
          rm -rf Payload && mkdir Payload
          cp -R Runner.app Payload/
          zip -r app_unsigned.ipa Payload
          mv app_unsigned.ipa $CM_ARTIFACTS_DIR/

    artifacts:
      - $CM_ARTIFACTS_DIR/app_unsigned.ipa
